# Generated by Django 4.1.7 on 2023-02-28 09:40

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employeeNo', models.CharField(editable=False, max_length=25, unique=True, verbose_name='Employee No.')),
                ('first_name', models.CharField(max_length=50, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=50, verbose_name='Last Name')),
                ('workEmail', models.EmailField(max_length=100, unique=True, verbose_name='Work Email')),
                ('personalEmail', models.EmailField(blank=True, max_length=100, null=True, unique=True, verbose_name='Personal Email')),
                ('mobile', phonenumber_field.modelfields.PhoneNumberField(max_length=15, region=None, unique=True, verbose_name='Mobile Phone')),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10, verbose_name='Gender')),
                ('bloodGroup', models.CharField(blank=True, max_length=10, null=True, verbose_name='Blood Group')),
                ('dob', models.DateField(verbose_name='Date of Birth')),
                ('maritalStatus', models.CharField(blank=True, choices=[('Single', 'Single'), ('Married', 'Married'), ('Divorced', 'Divorced')], max_length=10, null=True, verbose_name='Marital Status')),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to='static/ProfilePicture/', verbose_name='Profile Picture')),
                ('designation', models.CharField(max_length=100, verbose_name='Designation')),
                ('department', models.CharField(blank=True, max_length=100, null=True, verbose_name='Department')),
                ('dateOfJoin', models.DateField(verbose_name='Joining Date')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
