# Generated by Django 4.1.7 on 2023-02-28 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmployeeApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'verbose_name_plural': 'Employee Details'},
        ),
        migrations.AlterField(
            model_name='employee',
            name='personalEmail',
            field=models.EmailField(blank=True, max_length=100, null=True, verbose_name='Personal Email'),
        ),
    ]
